stages:
  - security
  - lint
  - tests
  - build
  - cve
  - publish

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - scheduler_failure
      - stuck_or_timeout_failure
      - api_failure
      - job_execution_timeout
      - data_integrity_failure

variables:
  REGISTRY_URL: "registry.home.chupin.xyz"
  GITLEAKS_VERSION: "latest"
  HELM_VERSION: "latest"
  TRIVY_VERSION: "latest"
  CHART_RELEASER_VERSION: "latest"

  TRIVY_SEVERITY: HIGH,CRITICAL
  IGNORE_TRIVY_CVE: true

  CR_GIT_REPO: ghostfolio-helm
  CR_SKIP_EXISTING: true

include:
  - local: .gitlab/build.yml
    rules:
      - if: "$CI_COMMIT_TAG == null"
  - local: .gitlab/release.yml
    rules:
      - if: $CI_COMMIT_TAG
