{{- $tokenSalt := .Values.ghostfolio.ACCESS_TOKEN_SALT | required ".Values.ghostfolio.ACCESS_TOKEN_SALT is required." -}}
{{- $secretKey := .Values.ghostfolio.JWT_SECRET_KEY | required ".Values.ghostfolio.JWT_SECRET_KEY is required." -}}
{{- $fullname := (include "ghostfolio.fullname" .) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghostfolio.fullname" . }}
  labels:
    {{- include "ghostfolio.labels" . | nindent 4 }}
stringData:
  # NPM CONFIGURATION FOR NON-ROOT USER
  NPM_CONFIG_CACHE: /tmp/npm-cache
  # CACHE
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ include "ghostfolio.redisHost" . | quote }}
  REDIS_PORT: "6379"
  {{- if not .Values.redis.auth.secretRef.name }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  {{- end }}
  {{- else }}
  REDIS_HOST: {{ .Values.externalRedis.host | quote }}
  REDIS_PORT: {{ .Values.externalRedis.port | quote }}
  {{- if not .Values.externalRedis.auth.secretRef.name }}
  REDIS_PASSWORD: {{ .Values.externalRedis.password | quote }}
  {{- end }}
  {{- end }}
  # DATABASE
  {{- if .Values.postgresql.enabled }}
  {{- if not .Values.postgresql.auth.secretRef.name}}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_HOST: {{ printf "%s-postgresql.%s.svc" $fullname .Release.Namespace | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_OPTIONS: sslmode=disable&connect_timeout=300
  {{- else }}
  {{- if not .Values.externalPostgresql.auth.secretRef.name}}
  POSTGRES_USER: {{ .Values.externalPostgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.externalPostgresql.auth.password | quote }}
  {{- end }}
  POSTGRES_DB: {{ .Values.externalPostgresql.auth.database | quote }}
  POSTGRES_HOST: {{ .Values.externalPostgresql.host | quote }}
  POSTGRES_PORT: {{ .Values.externalPostgresql.port | quote }}
  POSTGRES_OPTIONS: {{ .Values.externalPostgresql.options | quote }}
  {{- end }}
  # VARIOUS
  ACCESS_TOKEN_SALT: {{ $tokenSalt | quote }}
  JWT_SECRET_KEY: {{ $secretKey | quote }}
  BASE_CURRENCY: {{ .Values.ghostfolio.BASE_CURRENCY | quote }}
  API_KEY_COINGECKO_DEMO: {{ .Values.ghostfolio.API_KEY_COINGECKO_DEMO | quote }}
  API_KEY_COINGECKO_PRO: {{ .Values.ghostfolio.API_KEY_COINGECKO_PRO | quote }}
  HOST: {{ .Values.ghostfolio.HOST | quote }}
  PORT: {{ .Values.ghostfolio.PORT | quote }}
