{{- $fullname := (include "ghostfolio.fullname" .) -}}
{{- $secretName := printf "%s-configuration" $fullname -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- $accessTokenSalt := .Values.ghostfolio.ACCESS_TOKEN_SALT -}}
{{- if and (not $accessTokenSalt) $existingSecret -}}
{{- $accessTokenSalt = index $existingSecret.data "ACCESS_TOKEN_SALT" | b64dec -}}
{{- end -}}
{{- if not $accessTokenSalt -}}
{{- $accessTokenSalt = randAlphaNum 64 -}}
{{- end -}}
{{- $jwtSecretKey := .Values.ghostfolio.JWT_SECRET_KEY -}}
{{- if and (not $jwtSecretKey) $existingSecret -}}
{{- $jwtSecretKey = index $existingSecret.data "JWT_SECRET_KEY" | b64dec -}}
{{- end -}}
{{- if not $jwtSecretKey -}}
{{- $jwtSecretKey = randAlphaNum 64 -}}
{{- end -}}
{{- $ignoredKeys := list "ACCESS_TOKEN_SALT" "JWT_SECRET_KEY" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "ghostfolio.labels" . | nindent 4 }}
stringData:
  # NPM CONFIGURATION FOR NON-ROOT USER
  NPM_CONFIG_CACHE: /tmp/npm-cache
  # CACHE
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ include "ghostfolio.redisHost" . | quote }}
  REDIS_PORT: "6379"
  {{- if and (not .Values.redis.auth.secretRef.name) .Values.redis.auth.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  {{- end }}
  {{- else }}
  REDIS_HOST: {{ .Values.externalRedis.host | quote }}
  REDIS_PORT: {{ .Values.externalRedis.port | quote }}
  {{- if and (not .Values.externalRedis.auth.secretRef.name) .Values.externalRedis.auth.enabled }}
  REDIS_PASSWORD: {{ .Values.externalRedis.auth.password | quote }}
  {{- end }}
  {{- end }}
  # VARIOUS
  ACCESS_TOKEN_SALT: {{ $accessTokenSalt | quote }}
  JWT_SECRET_KEY: {{ $jwtSecretKey | quote }}
  {{- range $key, $value := .Values.ghostfolio }}
    {{- if not (has $key $ignoredKeys) }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-configuration-postgresql" $fullname }}
  labels:
    {{- include "ghostfolio.labels" . | nindent 4 }}
stringData:
  {{- if .Values.postgresql.enabled }}
  {{- if not .Values.postgresql.auth.secretRef.name}}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_HOST: {{ printf "%s-postgresql.%s.svc" $fullname .Release.Namespace | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_OPTIONS: sslmode=disable&connect_timeout=300
  {{- else }}
  {{- if not .Values.externalPostgresql.auth.secretRef.name}}
  POSTGRES_USER: {{ .Values.externalPostgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.externalPostgresql.auth.password | quote }}
  {{- end }}
  POSTGRES_DB: {{ .Values.externalPostgresql.auth.database | quote }}
  POSTGRES_HOST: {{ .Values.externalPostgresql.host | quote }}
  POSTGRES_PORT: {{ .Values.externalPostgresql.port | quote }}
  POSTGRES_OPTIONS: {{ .Values.externalPostgresql.options | quote }}
  {{- end }}
