apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghostfolio.fullname" . }}
  labels:
    {{- include "ghostfolio.labels" . | nindent 4 }}
stringData:
  # CACHE
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  # VARIOUS
  ACCESS_TOKEN_SALT: {{ .Values.ghostfolio.ACCESS_TOKEN_SALT | quote }}
  DATABASE_URL: {{ include "ghostfolio.databaseUrl" . | quote }}
  JWT_SECRET_KEY: {{ .Values.ghostfolio.JWT_SECRET_KEY | quote }}
  BASE_CURRENCY: {{ .Values.ghostfolio.BASE_CURRENCY | quote }}
  API_KEY_COINGECKO_DEMO: {{ .Values.ghostfolio.API_KEY_COINGECKO_DEMO | quote }}
  API_KEY_COINGECKO_PRO: {{ .Values.ghostfolio.API_KEY_COINGECKO_PRO | quote }}
  HOST: {{ .Values.ghostfolio.HOST | quote }}
  PORT: {{ .Values.ghostfolio.PORT | quote }}
